name: Common CI Setup
description: Sets up environment and dependencies for Niova-Mdsvc CI workflows.
runs:
    using: "composite"
    steps:

    - name: apt update
      run: sudo apt update
      shell: bash

    - name: dpkg / rpm prep
      run: sudo -E apt-get install -y uuid-dev uuid libuuid1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0
      shell: bash

    # Install golang
    - name: Install golang 1.20.3
      run: sudo rm -rf /usr/bin/go &&
           sudo wget https://golang.org/dl/go1.23.0.linux-amd64.tar.gz &&
           sudo mkdir /home/runner/work/go &&
           sudo tar -C /home/runner/work/go -xzf  go1.23.0.linux-amd64.tar.gz &&
           export PATH=$PATH:/home/runner/work/go/go/bin &&
           go version
      shell: bash

    # Install Ansible
    - name: Install Ansible
      run:  pip3 install ansible==9.2
      shell: bash

    # Install python libraries
    - name: Install python libraries
      run:  pip3 install setuptools wheel func_timeout sockets psutil dpath jmespath
      shell: bash

    - name: build libbacktrace
      run: cd modules/niova-pumicedb/modules/libbacktrace/ && 
           ./configure && 
           make && sudo make install
      shell: bash

    # Build niova-core for niova-raft
    - name: Build niova-core
      run: cd modules/niova-pumicedb/modules/niova-raft/modules/niova-core/ && 
           ./prepare.sh && 
           ./configure --enable-devel --prefix=/home/runner/work/niovad/niovad/build_dir/ && 
           make -j 4 && 
           make -j 4 check && 
           make install
      shell: bash

    - name: Build niova-raft
      run: cd modules/niova-pumicedb/modules/niova-raft/ &&
           ./prepare.sh &&
           ./configure --with-niova=/home/runner/work/niovad/niovad/build_dir/ --prefix=/home/runner/work/niovad/niovad/build_dir/ --enable-devel &&
           make clean && 
           make -j 4 && 
           make install
      shell: bash

    - name: Build niova-pumicedb
      run: cd modules/niova-pumicedb/ &&
           ./prepare.sh &&
           ./configure --enable-devel --with-niova=/home/runner/work/niovad/niovad/build_dir/ --prefix=/home/runner/work/niovad/niovad/build_dir/ &&
           make clean && make -j 4 && make install
      shell: bash
    
    - name: Build go applications using makefile
      run: export PATH=$PATH:/home/runner/work/go/go/bin && make -e DIR=/home/runner/work/niovad/niovad/build_dir
      shell: bash

      env:
        LD_LIBRARY_PATH: /home/runner/work/niovad/niovad/build_dir/lib

    - name: Copy script to run recipes
      run: cp scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/ &&
           cp scripts/controlplane_recipes.txt /home/runner/work/niovad/niovad/build_dir/
      shell: bash

    # Checkout holon repo
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
       repository: 00pauln00/holon
       path: ./holon

    - name: Copy holon repo
      run: cp -r ./holon /home/runner/work/niovad/niovad/build_dir/
      shell: bash

    - name: Create log directory for storing holon logs
      run: mkdir  /home/runner/work/niovad/niovad/holon_log
      shell: bash

    - name: Create dir for cover data counters, metadata to be placed
      run: mkdir  /home/runner/work/niovad/niovad/code_cov &&
           export GOCOVERDIR=/work/niovad/niovad/code_cov
      shell: bash
