version: "3.9"

services:
  node1:
    build: .
    container_name: controlplane_node1
    command: ["0"]  # container index
    volumes:
      - ./configs:/controlplane/configs
      - ./logs/node1:/controlplane/logs
    network_mode: "host"

  node2:
    build: .
    container_name: controlplane_node2
    command: ["1"]
    volumes:
      - ./configs:/controlplane/configs
      - ./logs/node2:/controlplane/logs
    network_mode: "host"

  node3:
    build: .
    container_name: controlplane_node3
    command: ["2"]
    volumes:
      - ./configs:/controlplane/configs
      - ./logs/node3:/controlplane/logs
    network_mode: "host"

  node4:
    build: .
    container_name: controlplane_node4
    command: ["3"]
    volumes:
      - ./configs:/controlplane/configs
      - ./logs/node4:/controlplane/logs
    network_mode: "host"

  node5:
    build: .
    container_name: controlplane_node5
    command: ["4"]
    volumes:
      - ./configs:/controlplane/configs
      - ./logs/node5:/controlplane/logs
    network_mode: "host"

