package userlib

import (
	"encoding/base64"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateSecretKey(t *testing.T) {
	t.Run("GeneratesValidKey", func(t *testing.T) {
		key, err := GenerateSecretKey()
		require.NoError(t, err)
		assert.NotEmpty(t, key)

		// Verify it's valid base64
		decoded, err := base64.RawStdEncoding.DecodeString(key)
		require.NoError(t, err)
		assert.Equal(t, SecretKeyLength, len(decoded), "Decoded key should be %d bytes", SecretKeyLength)
	})

	t.Run("GeneratesUniqueKeys", func(t *testing.T) {
		// Generate multiple keys and verify they're unique
		keys := make(map[string]bool)
		iterations := 100

		for i := 0; i < iterations; i++ {
			key, err := GenerateSecretKey()
			require.NoError(t, err)
			assert.False(t, keys[key], "Generated duplicate key: %s", key)
			keys[key] = true
		}

		assert.Equal(t, iterations, len(keys), "Should generate %d unique keys", iterations)
	})

	t.Run("GeneratesCorrectLength", func(t *testing.T) {
		key, err := GenerateSecretKey()
		require.NoError(t, err)

		// Base64 encoding of 16 bytes should be 22 characters (without padding)
		expectedEncodedLength := 22
		assert.Equal(t, expectedEncodedLength, len(key), "Base64 encoded key should be %d characters", expectedEncodedLength)
	})

	t.Run("GeneratedKeyIsValid", func(t *testing.T) {
		key, err := GenerateSecretKey()
		require.NoError(t, err)
		assert.True(t, ValidateKey(key), "Generated key should pass validation")
	})
}

func TestValidateKey(t *testing.T) {
	// Generate a valid key for testing
	validKey, _ := GenerateSecretKey()

	tests := []struct {
		name     string
		key      string
		expected bool
	}{
		{
			name:     "ValidKey",
			key:      validKey, // Valid key generated by GenerateSecretKey
			expected: true,
		},
		{
			name:     "EmptyKey",
			key:      "",
			expected: false,
		},
		{
			name:     "TooShort",
			key:      "c2hvcnRrZXk", // "shortkey" - only 8 bytes when decoded
			expected: false,
		},
		{
			name:     "TooLong",
			key:      "dGhpc2lzYXZlcnlsb25na2V5dGhhdGlzbW9yZXRoYW4xNmJ5dGVz", // More than 16 bytes
			expected: false,
		},
		{
			name:     "InvalidBase64",
			key:      "invalid!@#$%^&*()",
			expected: false,
		},
		{
			name:     "ValidBase64ButWrongLength",
			key:      "MTIzNDU2Nzg5MA", // Valid base64 but wrong length
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := ValidateKey(tt.key)
			assert.Equal(t, tt.expected, result)
		})
	}
}
